#!/bin/sh -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin 

case "$1" in
    configure)
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

# if package is newly installed, link install to web/install
if [ -z "$2" ]; then
    [ -e /opt/testlink/web/install ] || cp -a /opt/testlink/install /opt/testlink/web/
    a2ensite testlink
    if [ ! -f /opt/testlink/web/custom_config.inc.php ]; then
      cp /opt/testlink/web/custom_config.inc.php.example \
         /opt/testlink/web/custom_config.inc.php || true
    fi
fi

#DEBHELPER#

exit 0
