
require 'docbones'
source_suffix = '.rst'
::Docbones.setup source_suffix

PROJ.root= "."
PROJ.name = "admin_guide"
PROJ.index = "admin_guide"
PROJ.output = "../output/admin_guide"
PROJ.images = "images"
PROJ.pdf_font = "simhei.ttf"
PROJ.css_path = "/stylesheet/lightbox/nf.lightbox.css,/stylesheet/ossxp/doc.css"
PROJ.js_path = "/javascript/jquery/1.4.2.js,/javascript/lightbox/nf.lightbox.js,/javascript/lightbox/load-nf.lightbox.js"

task:default 
